# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
