# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import life.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mileStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=life.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('IncidentStartDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('IncidentEndDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Emotion', models.CharField(choices=[('H', 'HAPPY'), ('S', 'SAD'), ('A', 'ANGRY'), ('J', 'JOY'), ('E', 'EXCITED'), ('X', 'ANXIETY'), ('B', 'BLUE'), ('P', 'PANIC'), ('C', 'CHILLING'), ('R', 'RELAX')], max_length=1)),
            ],
            options={
                'ordering': ['-IncidentStartDate'],
            },
        ),
        migrations.CreateModel(
            name='mileStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyTitle', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=150)),
                ('startDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('targetDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=life.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startDate'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('a', 'Agender'), ('b', 'Bigender'), ('f', 'Gender-fluid')], max_length=1)),
                ('self_introduction', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=life.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='parentStory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.mileStory'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
